# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48cd26c331b42bf460e1cf110cbb787e32163fa7809705ab1007f17854cbdce13e98c7add51feb7a1f99cdda73610af78f6dd0249b97da310e1eef73198e07f6

test:
  secret_key_base: 8510dc7345713c517b9d6c973b0470482679a30b6471f49487f3774c8a1f83822bd34fe3600109748d4109f87992697263eb3e18d3e89a36839a3722ec40b798

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
